name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkoutt
        uses: actions/checkout@master
      - name: Archieve code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.txt
